# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='\u4e3b\u673a\u540d')),
                ('innerip', models.CharField(max_length=32)),
                ('outerip', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'host',
                'verbose_name': '\u4e3b\u673a\u8868',
                'verbose_name_plural': '\u4e3b\u673a\u8868',
            },
        ),
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32)),
                ('operate_name', models.CharField(max_length=32)),
                ('public_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-public_time'],
                'db_table': 'loginfo',
                'verbose_name': '\u64cd\u4f5c\u65e5\u5fd7\u8868',
                'verbose_name_plural': '\u64cd\u4f5c\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('pro_src', models.CharField(max_length=32, verbose_name='\u9879\u76ee\u6e90\u5730\u5740')),
                ('pro_dest', models.CharField(max_length=32, verbose_name='\u9879\u76ee\u76ee\u6807\u5730\u5740')),
                ('module', models.CharField(max_length=32, verbose_name='rsync\u6a21\u5757')),
                ('creater', models.CharField(max_length=32, verbose_name='\u521b\u5efa\u4eba')),
                ('description', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'project',
                'verbose_name': '\u9879\u76ee\u8868',
                'verbose_name_plural': '\u9879\u76ee\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userinfo',
                'verbose_name': '\u8d26\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u8d26\u6237\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project'),
        ),
    ]
