# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20161205_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='create_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
