# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_loginfo_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginfo',
            name='create_time',
        ),
    ]
