# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_loginfo_operate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='module',
        ),
    ]
